### ISSUE TITLE
Cocoapods please!

### ISSUE THREAD

**Issue by lfarah** [taglia3/ParallaxCarousel#1]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by taglia3** [comment]
Hi Lucas,
thanks for the tip! 
Support cocoapods is already in my plans. It will be supported in the next days.

**Comment by taglia3** [comment]
HI,
CocoaPods is now available!
