### ISSUE TITLE
Swift 3 branch?

### ISSUE THREAD

**Issue by the-freshlord** [taglia3/ParallaxCarousel#7]
Is there a Swift 3 branch?

**Comment by taglia3** [comment]
Hi Emanuel,

I'll do it the next week.

Thanks,
Matteo

**Comment by hemant3370** [comment]
@eman6576 I have converted the Main class and not the example. https://github.com/taglia3/TGLParallaxCarousel/pull/8

**Comment by taglia3** [comment]
Hi Emanuel,

the carousel project now is in Swift 3.

Matteo
